name: Favorites Updater

on: [push]
  # schedule:
      # - cron: "0 0 * * 6"
      # 毎週土曜日の午前0時に起動

jobs:
  Updater:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'npm'
    
    - name: Installing dependencies
      run: npm install

    - name: Create dotenv file
      shell: bash
      run: touch .env | 
        echo "BOOKMETER_ACCOUNT=${{ secrets.BOOKMETER_ACCOUNT }}" >> .env
        echo "BOOKMETER_PASSWORD=${{ secrets.BOOKMETER_PASSWORD }}" >> .env
        echo "CINII_API_APPID=${{ secrets.CINII_API_APPID }}" >> .env
        echo "BOUNDHUB_ACCOUNT=${{ secrets.BOUNDHUB_ACCOUNT }}" >> .env
        echo "BOUNDHUB_PASSWORD=${{ secrets.BOUNDHUB_PASSWORD }}" >> .env
        echo "NOTE_ACCOUNT=${{ secrets.NOTE_ACCOUNT }}" >> .env
        echo "NOTE_PASSWORD=${{ secrets.NOTE_PASSWORD }}" >> .env
        echo "TERATAIL_API_TOKEN=${{ secrets.TERATAIL_API_TOKEN }}" >> .env
        echo "ZENN_GOOGLE_ACCOUNT=${{ secrets.ZENN_GOOGLE_ACCOUNT }}" >> .env
        echo "ZENN_GOOGLE_PASSWORD=${{ secrets.ZENN_GOOGLE_PASSWORD }}" >> .env
        echo "TWITTER_ACCOUNT=${{ secrets.TWITTER_ACCOUNT }}" >> .env
        echo "TWITTER_PASSWORD=${{ secrets.TWITTER_PASSWORD }}" >> .env
    
    - name: GitHub Stars
      shell: bash
      working-directory: ./github_stars
      run: bash ./wget_github_stars.sh

    - name: Qiita LGTM
      shell: bash
      working-directory: ./qiita_lgtm
      run: node ./puppeteer_qiita.js

    - name: Bookmeter Wished Books
      shell: bash
      working-directory: ./bookmeter_wish
      run: node ./puppeteer_bookmeter.js
        # ./is_in_sophia.sh
        # CSVをどうやっていじるか考える

    - name: BoundHub Faved Movies
      shell: bash
      working-directory: ./boundhub
      run: node ./puppeteer_boundhub.js | 
        bash ./get_url_list.sh

    - name: note Faved Articles
      shell: bash
      working-directory: ./note_favs
      run: node ./puppeteer_note.js

    - name: Zenn Faved Articles
      shell: bash
      working-directory: ./zenn_favs
      run: node ./puppeteer_zenn.js

    - name: Set the current datetime
      env:
        TZ: 'Asia/Tokyo'
      run: echo "CURRENT_DATETIME=$(date --iso-8601=minutes)" >> $GITHUB_ENV
    
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with: 
        commit_message: 'updated: ${{ env.CURRENT_DATETIME }}'
        branch: automated-actions
