name: Favorites Updater

on: [push]
  # schedule:
      # - cron: "0 0 * * 6"
      # 毎週土曜日の午前0時に起動

jobs:
  Updater:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'npm'
    
    - name: Installing dependencies
      run: npm install

    - name: Create dotenv file
      shell: bash
      run: touch .env | 
        echo "BOOBOOKMETER_ACCOUNT=${{ secrets.BOOKMETER_ACCOUNT }}" >> .env
        echo "BOOKMETER_PASSWORD=${{ secrets.BOOKMETER_PASSWORD }}" >> .env
        echo "CINII_API_APPID=${{ secrets.CINII_API_APPID }}" >> .env
        echo "BOUNDHUB_ACCOUNT=${{ secrets.BOUNDHUB_ACCOUNT }}" >> .env
        echo "BOUNDHUB_PASSWORD=${{ secrets.BOUNDHUB_PASSWORD }}" >> .env
        echo "NOTE_ACCOUNT=${{ secrets.NOTE_ACCOUNT }}" >> .env
        echo "NOTE_PASSWORD=${{ secrets.NOTE_PASSWORD }}" >> .env
        echo "TERATAIL_API_TOKEN=${{ secrets.TERATAIL_API_TOKEN }}" >> .env
        echo "ZENN_GOOGLE_ACCOUNT=${{ secrets.ZENN_GOOGLE_ACCOUNT }}" >> .env
        echo "ZENN_GOOGLE_PASSWORD=${{ secrets.ZENN_GOOGLE_PASSWORD }}" >> .env
    
    - name: GitHub Stars
      shell: bash
      run: cd ./github_stars | 
        ./wget_github_stars.sh

    - name: Qiita LGTM
      shell: bash
      run: cd ../qiita_lgtm | 
        node ./puppeteer_qiita.js

    - name: Bookmeter Wished Books
      shell: bash
      run: cd ../bookmeter_wish | 
        node ./puppeteer_bookmeter.js
        # ./is_in_sophia.sh
        # CSVをどうやっていじるか考える

    - name: BoundHub Faved Movies
      shell: bash
      run: cd ../boundhub | 
        node ./puppeteer_boundhub.js
        bash ./get_url_list.sh

    - name: note Faved Articles
      shell: bash
      run: cd ../note_favs | 
        node ./puppeteer_note.js

    - name: Zenn Faved Articles
      shell: bash
      run: cd ../zenn_favs | 
        node ./puppeteer_zenn.js

    - name: Set the current datetime
      env:
        TZ: 'Asia/Tokyo'
      run: echo "CURRENT_DATETIME=$(date --iso-8601=minutes)" >> $GITHUB_ENV
    
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with: 
        commit_message: 'updated: ${{ env.CURRENT_DATETIME }}'
